const playlist =[
    "https://jetsetradio.live/radio/stations/lofi/90sFlav - Balmy.mp3",
    "https://jetsetradio.live/radio/stations/lofi/90sFlav - Call Me.mp3",
    "https://jetsetradio.live/radio/stations/lofi/Adam Kay - Rehab (Instrumental).mp3",
    "https://jetsetradio.live/radio/stations/lofi/Aekasoro - Almost there.mp3",
    "https://jetsetradio.live/radio/stations/lofi/Afternoon - spring (w park bird).mp3",
    "https://jetsetradio.live/radio/stations/lofi/Aftrthght - I think of you when I.mp3",
    "https://jetsetradio.live/radio/stations/lofi/Altitude - Lake serene.mp3",
    // "https://jetsetradio.live/radio/stations/lofi/Amber - Little by little.mp3",
    // "https://jetsetradio.live/radio/stations/lofi/Angel - I got your back.mp3",
    // "https://jetsetradio.live/radio/stations/lofi/Antony - Being on your way.mp3",
    "https://jetsetradio.live/radio/stations/lofi/App - My First.mp3",
    "https://jetsetradio.live/radio/stations/lofi/Aqualina - Love Letters W-e1.mp3",
    "https://jetsetradio.live/radio/stations/lofi/Aso - Coffee.mp3",
    "https://jetsetradio.live/radio/stations/lofi/Athena - One side..mp3",
    "https://jetsetradio.live/radio/stations/lofi/Basil - To all the ladies in.mp3",
    "https://jetsetradio.live/radio/stations/lofi/Bknapp - Game Over (Super Mario lofi).mp3",
    "https://jetsetradio.live/radio/stations/lofi/blvknight - december.mp3",
    "https://jetsetradio.live/radio/stations/lofi/Burbank - A Beautiful Name.mp3",
    "https://jetsetradio.live/radio/stations/lofi/Burbank - Moonlights.mp3"
    "https://jetsetradio.live/radio/stations/lofi/Burbank - The Shadow of Your Smile.mp3",
    "https://jetsetradio.live/radio/stations/lofi/Cat naps - hazy dreams.mp3",
]